### PR TITLE
W-13588449: Parse template target value breaking change. (#1200)

### PR DESCRIPTION
**Pull request by IvanAndresFritzler**
(cherry picked from commit be3e2bc06b323e55c2cc901f8bbd048fa9a4887a)

### CODE REVIEW

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Review by fsgonz — APPROVED** [review]

**Review by fsgonz — APPROVED** [review]

**Pull request merged**
